FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8

LABEL maintainer="toodofun@toodofun.com"

ARG TARGETARCH

COPY _output/pulse-${TARGETARCH} /usr/bin/pulse
COPY LICENSE /licenses/LICENSE

RUN  \
     microdnf update --nodocs --assumeyes && \
     microdnf install ca-certificates --nodocs --assumeyes && \
     microdnf clean all

ENTRYPOINT ["pulse"]